version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  express:
    build: ./express
    volumes:
      - ./express:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
