version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db  
    networks:
      - app

  express:
    build: ./express
    container_name: express
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app   
    depends_on:
      - mongodb
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html  
      - ./nginx/nginx.conf:/etc/nginx/default.conf 
    depends_on:
      - express
    networks:
      - app

networks:
  app:
    driver: bridge