version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb_data:/data/db  # Mount volume to store data on host machine
    ports:
      - "27017:27017"
      
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html  # Mount HTML files on host machine
      - ./nginx/conf:/etc/nginx/conf.d      # Mount config files on host machine
    ports:
      - "8080:80"
    depends_on:
      - express
    
  express:
    image: node:16
    container_name: express
    restart: always
    volumes:
      - ./express:/usr/src/app  # Mount express application to host machine
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  nginx_html:
  express_code:
